version: 0.2

env:
  variables:
    NODE_OPTIONS: "--max_old_space_size=4096"

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - touch .env
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - '**/*'
