version: 0.2

env:
  variables:
    NODE_OPTIONS: "--max_old_space_size=4096"

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn
  post_build:
    commands:
      - echo Build completed on `date`
      - touch .env
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - '**/*'
